/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VivaRouteImport } from './routes/viva'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as SafetynetRouteImport } from './routes/safetynet'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as RedflagsRouteImport } from './routes/redflags'
import { Route as QaRouteImport } from './routes/qa'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ExaminerRouteImport } from './routes/examiner'
import { Route as ExaminationRouteImport } from './routes/examination'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as PracticeSoloRouteImport } from './routes/practice.solo'
import { Route as PracticeActorExaminerRouteImport } from './routes/practice.actor-examiner'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'

const VivaRoute = VivaRouteImport.update({
  id: '/viva',
  path: '/viva',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetynetRoute = SafetynetRouteImport.update({
  id: '/safetynet',
  path: '/safetynet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const RedflagsRoute = RedflagsRouteImport.update({
  id: '/redflags',
  path: '/redflags',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminerRoute = ExaminerRouteImport.update({
  id: '/examiner',
  path: '/examiner',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationRoute = ExaminationRouteImport.update({
  id: '/examination',
  path: '/examination',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const PracticeSoloRoute = PracticeSoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeActorExaminerRoute = PracticeActorExaminerRouteImport.update({
  id: '/actor-examiner',
  path: '/actor-examiner',
  getParentRoute: () => PracticeRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/examination': typeof ExaminationRoute
  '/examiner': typeof ExaminerRoute
  '/generate': typeof GenerateRoute
  '/learn': typeof LearnRoute
  '/letter': typeof LetterRoute
  '/patient': typeof PatientRoute
  '/performance': typeof PerformanceRoute
  '/practice': typeof PracticeRouteWithChildren
  '/protocols': typeof ProtocolsRoute
  '/qa': typeof QaRoute
  '/redflags': typeof RedflagsRoute
  '/references': typeof ReferencesRoute
  '/safetynet': typeof SafetynetRoute
  '/scope': typeof ScopeRoute
  '/viva': typeof VivaRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/practice/actor-examiner': typeof PracticeActorExaminerRoute
  '/practice/solo': typeof PracticeSoloRoute
  '/cases/': typeof CasesIndexRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examination': typeof ExaminationRoute
  '/examiner': typeof ExaminerRoute
  '/generate': typeof GenerateRoute
  '/learn': typeof LearnRoute
  '/letter': typeof LetterRoute
  '/patient': typeof PatientRoute
  '/performance': typeof PerformanceRoute
  '/protocols': typeof ProtocolsRoute
  '/qa': typeof QaRoute
  '/redflags': typeof RedflagsRoute
  '/references': typeof ReferencesRoute
  '/safetynet': typeof SafetynetRoute
  '/scope': typeof ScopeRoute
  '/viva': typeof VivaRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/practice/actor-examiner': typeof PracticeActorExaminerRoute
  '/practice/solo': typeof PracticeSoloRoute
  '/cases': typeof CasesIndexRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/examination': typeof ExaminationRoute
  '/examiner': typeof ExaminerRoute
  '/generate': typeof GenerateRoute
  '/learn': typeof LearnRoute
  '/letter': typeof LetterRoute
  '/patient': typeof PatientRoute
  '/performance': typeof PerformanceRoute
  '/practice': typeof PracticeRouteWithChildren
  '/protocols': typeof ProtocolsRoute
  '/qa': typeof QaRoute
  '/redflags': typeof RedflagsRoute
  '/references': typeof ReferencesRoute
  '/safetynet': typeof SafetynetRoute
  '/scope': typeof ScopeRoute
  '/viva': typeof VivaRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/practice/actor-examiner': typeof PracticeActorExaminerRoute
  '/practice/solo': typeof PracticeSoloRoute
  '/cases/': typeof CasesIndexRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/examination'
    | '/examiner'
    | '/generate'
    | '/learn'
    | '/letter'
    | '/patient'
    | '/performance'
    | '/practice'
    | '/protocols'
    | '/qa'
    | '/redflags'
    | '/references'
    | '/safetynet'
    | '/scope'
    | '/viva'
    | '/cases/$caseId'
    | '/practice/actor-examiner'
    | '/practice/solo'
    | '/cases/'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examination'
    | '/examiner'
    | '/generate'
    | '/learn'
    | '/letter'
    | '/patient'
    | '/performance'
    | '/protocols'
    | '/qa'
    | '/redflags'
    | '/references'
    | '/safetynet'
    | '/scope'
    | '/viva'
    | '/cases/$caseId'
    | '/practice/actor-examiner'
    | '/practice/solo'
    | '/cases'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/examination'
    | '/examiner'
    | '/generate'
    | '/learn'
    | '/letter'
    | '/patient'
    | '/performance'
    | '/practice'
    | '/protocols'
    | '/qa'
    | '/redflags'
    | '/references'
    | '/safetynet'
    | '/scope'
    | '/viva'
    | '/cases/$caseId'
    | '/practice/actor-examiner'
    | '/practice/solo'
    | '/cases/'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  ExaminationRoute: typeof ExaminationRoute
  ExaminerRoute: typeof ExaminerRoute
  GenerateRoute: typeof GenerateRoute
  LearnRoute: typeof LearnRoute
  LetterRoute: typeof LetterRoute
  PatientRoute: typeof PatientRoute
  PerformanceRoute: typeof PerformanceRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  ProtocolsRoute: typeof ProtocolsRoute
  QaRoute: typeof QaRoute
  RedflagsRoute: typeof RedflagsRoute
  ReferencesRoute: typeof ReferencesRoute
  SafetynetRoute: typeof SafetynetRoute
  ScopeRoute: typeof ScopeRoute
  VivaRoute: typeof VivaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viva': {
      id: '/viva'
      path: '/viva'
      fullPath: '/viva'
      preLoaderRoute: typeof VivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safetynet': {
      id: '/safetynet'
      path: '/safetynet'
      fullPath: '/safetynet'
      preLoaderRoute: typeof SafetynetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redflags': {
      id: '/redflags'
      path: '/redflags'
      fullPath: '/redflags'
      preLoaderRoute: typeof RedflagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examiner': {
      id: '/examiner'
      path: '/examiner'
      fullPath: '/examiner'
      preLoaderRoute: typeof ExaminerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examination': {
      id: '/examination'
      path: '/examination'
      fullPath: '/examination'
      preLoaderRoute: typeof ExaminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/practice/solo': {
      id: '/practice/solo'
      path: '/solo'
      fullPath: '/practice/solo'
      preLoaderRoute: typeof PracticeSoloRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/actor-examiner': {
      id: '/practice/actor-examiner'
      path: '/actor-examiner'
      fullPath: '/practice/actor-examiner'
      preLoaderRoute: typeof PracticeActorExaminerRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface PracticeRouteChildren {
  PracticeActorExaminerRoute: typeof PracticeActorExaminerRoute
  PracticeSoloRoute: typeof PracticeSoloRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeActorExaminerRoute: PracticeActorExaminerRoute,
  PracticeSoloRoute: PracticeSoloRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  ExaminationRoute: ExaminationRoute,
  ExaminerRoute: ExaminerRoute,
  GenerateRoute: GenerateRoute,
  LearnRoute: LearnRoute,
  LetterRoute: LetterRoute,
  PatientRoute: PatientRoute,
  PerformanceRoute: PerformanceRoute,
  PracticeRoute: PracticeRouteWithChildren,
  ProtocolsRoute: ProtocolsRoute,
  QaRoute: QaRoute,
  RedflagsRoute: RedflagsRoute,
  ReferencesRoute: ReferencesRoute,
  SafetynetRoute: SafetynetRoute,
  ScopeRoute: ScopeRoute,
  VivaRoute: VivaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
